import type { Metadata } from "next";
import { Lora, Montserrat } from "next/font/google";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { cn } from "core/utils/cn";
import { getMessages } from "next-intl/server";
import { ThemeProvider } from "./theme-provider";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-primary",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: ReactNode;
  params: { locale: string };
};
export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      className={cn(lora.variable, montserrat.variable)}
      suppressContentEditableWarning
    >
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className="font-secondary">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
